  version: '3'
  services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        environment:
        - JENKINS_OPTS="--prefix=/jenkins"
        ports:
        - 8080:8080
        - 50000:50000
    
        volumes:
        - /root/jenkins_compose/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock